---
title: "mi_segundo_archivo.R"
author: "Dalexna"
format: html
editor: visual
---

```{r}
# Definimos una función llamada 'suma' que recibe dos argumentos: 'numero1' y 'numero2'
suma <- function(numero1, numero2 = 0) {
  # Realizamos la suma de los dos números
  resultado <- numero1 + numero2
  
  # Devolvemos el resultado
  return(resultado)
}

```

```{r}
# Llamamos a la función 'suma' con dos argumentos
resultado1 <- suma(5, 3)
print(resultado1) 
# Devolverá: [1] 8

```

```{r}
# Llamamos a la función 'suma' con solo un argumento (se usará el valor predeterminado de 'numero2')
resultado2 <- suma(5)
print(resultado2) # Devolverá: [1] 5
```

```{r}
## función 
#comentario : la funcion le falataba el parentesis de cierre en la funcion return y el colchete de apertura de funcion

calculo_inflacion <- function(precios_anterior, precios_actual) {
  
  # Calculamos la inflación para cada artículo
  inflacion <- ((precios_actual / precios_anterior) - 1) * 100
  
  # Retornamos el valor
  return(inflacion)
  # no es corchete, es el símbolo de llave { o }
```

```{r}

# Faltó el símbolo de llave en el cierre. Sino lo colocas no vas a poder obtener los valores en el chink siguiente

calculo_inflacion <- function(precios_anterior, precios_actual) {
  
  # Calculamos la inflación para cada artículo
  inflacion <- ((precios_actual / precios_anterior) - 1) * 100
  
  # Retornamos el valor
  return(inflacion)
}

# no es corchete, es el símbolo de  llave
```

```{r}
# Ejemplo de uso
# Si la función definida en el chunk anterior no se completó correctamente no se podrá ejecutar ninguno de los chunks siguientes
print(calculo_inflacion(10, 14)) 
print(calculo_inflacion(12, 9))
```

```{r}
#le faltaba un signo igual a la asiganacion del precio actual
calculo_inflacion(precios_anterior =10, precios_actual = 14)
```

```{r}
#le faltaba un parentesis para cerrar la funcion
calculo_inflacion(precios_actual =20, 
                  precios_anterior= 21)
```

```{r}
# a esta linea de codigo le faltaba la variable poblacion en la function y la variable pib_total en la division 

calcular_pib_per_capita <- function(pib_total,poblacion) {
  # Calculamos el PIB per cápita
  pib_per_capita <- pib_total / poblacion
  
  return(pib_per_capita)
}
```

```{r}
# Ejemplo de uso
pib_total <- 123000043  # PIB total en millones de dólares
poblacion <- 24531    # Población en millones

pib_per_capita_resultado <- calcular_pib_per_capita(pib_total, poblacion)

print(pib_per_capita_resultado)  # Imprimir el resultado
```

```{r}
# Ejemplo de uso 2 
# cambie el nombre de las variables para no sobreescribir y le cs cambie el monto a cada una para q me diera un resultado distinto 

pib_total_2 <- 3456000  # PIB total en millones de dólares
poblacion_2 <- 3000    # Población en millones

pib_per_capita_resultado_2 <- calcular_pib_per_capita(pib_total_2, poblacion_2)

print(pib_per_capita_resultado_2)  # Imprimir el resultado

```
