---
title: "Practica_1_clase_6"
author: "nayuha_palenzuela"
format: html
editor: visual
---

## Ejercicios Prácticos

### 1. Creación de Archivos con Comentarios

#### Ejercicio 1.1

```{r}
# Vector numérico
numeros <- c(1, 2, 3, 4, 5)
# la variable se llama numeros y su contenido es 1, 2, 3, 4, 5

```

```{r}
# Vector de caracteres
dias_semana <- c("lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo")

# la variable se llama dias_semana y su contenido es "lunes", "martes",....
# prestar atención a comillas al inicio y final de cada día de la semana
```

```{r}

# vectores con la fecha
fechas_nacimiento <- c('2010-01-01', "2005-06-10",'1999-10-31')

# prestar atención al uso de comillas simples y dobles
```

#### Corrección

```{r}

# descomentar línea de abajo (quitar numeral)
#numeros_pares <- c(2, 4, 6, , 10)

# te faltó descomentar la línea anterior
```

```{r}
# descomentar línea de abajo (quitar numeral)
# mis_frutas <- c('manzana', "banana", 'uva')

# te faltó descomentar la línea anterior (quitar numeral)
```

```{r}
# descomentar línea de abajo (quitar numeral)
mayor_que_cinco <- c(6, 8, 10)
```

#### **- Crear un vector numérico:**

```{r}
numero_par <- c(2, 4, 6, 8, 10)
# pudiste usar la función seq
seq(from= 2, to= 10, by=2)

numero_impar <- c(1, 3, 5, 7, 9)
#igualmente en este caso
seq(from= 1, to= 9,by=2)


```

#### - **Crear un vector de caracteres:**

```{r}
nombre_facultad_de_la_universidad <- c('Facultad de Ciencias Económicas y sociales','Universidad Central de Venezuela')
```

```{r}
nombre_de_los_primeros_meses <- c("enero", "febrero", "marzo")
```

#### -Crear un vector Lógico

```{r}
vector_de_numeros <- c(1:5)
vector_de_numeros>3
# bien!
```

```{r}
vector_de_banana <- c("banana")
vector_de_banana == "a"

#la cosa es por acá
c('b','a','n','a','n','a')=='a'
```

#### - Crear vector de fechas

```{r}
fechas_primer_día_ultimo_dia <- c("01-01-2024","31-01-2024","01-02-2024","29-02-2024","01-03-2024","31-03-2024")

# lo importante es que tengas en cuenta que en las fechas, primero debe ir el año, luego el mes y finalmente el día.
# Si usas al la función Sys.Date() podrás verificar lo que te estoy comentando
```
